// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJlQgKUWtdJpOGBBix1qGZ6k8Um8VLmk',
    appId: '1:1003291557669:web:acac09b20b2c0c933924cc',
    messagingSenderId: '1003291557669',
    projectId: 'flutter-speed',
    authDomain: 'flutter-speed.firebaseapp.com',
    databaseURL: 'https://flutter-speed-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-speed.appspot.com',
    measurementId: 'G-LYCKR382K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9m2b7L-W-ojsUVHZjrXc-nmGjXq6FVQI',
    appId: '1:1003291557669:android:888cef2c5df10a483924cc',
    messagingSenderId: '1003291557669',
    projectId: 'flutter-speed',
    databaseURL: 'https://flutter-speed-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-speed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdh8OBjWIrkm5IDeYbDtsaYMq5CxJBpOk',
    appId: '1:1003291557669:ios:2c08075d13a7f09e3924cc',
    messagingSenderId: '1003291557669',
    projectId: 'flutter-speed',
    databaseURL: 'https://flutter-speed-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-speed.appspot.com',
    iosBundleId: 'com.example.vesion6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdh8OBjWIrkm5IDeYbDtsaYMq5CxJBpOk',
    appId: '1:1003291557669:ios:bc3b60d3da3f45b33924cc',
    messagingSenderId: '1003291557669',
    projectId: 'flutter-speed',
    databaseURL: 'https://flutter-speed-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-speed.appspot.com',
    iosBundleId: 'com.example.vesion6.RunnerTests',
  );
}
